Add missing context to raw block transfer function calls.
eclipse/wakaama pull request #582
Opened 2021-04-10 20:32 UTC by pehrnord

Signed-off-by: Pehr Nord <pehr.nord@husqvarnagroup.com>

2021-04-11 08:21 UTC, rettichschnidi requested changes
Thanks for the input!

My feedback:
* The error being fixed here could only get into the code base because LWM2M_RAW_BLOCK1_REQUESTS was never enabled in any of the targets. In order to merge this PR, this should be addresses.
<s>I know @mlasch is working on something in this area - maybe he wants to chime in?</s>
* You need to sign the commits using an e-mail address which is signed up at Eclipse and has accepted the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php).

2021-04-15 12:50 UTC, pehrnord commented
Signed up and accepted ECA.
Not sure how to proceed on you other comment, would a new unittest need to be added?

2021-04-16 10:46 UTC, rettichschnidi commented
> Signed up and accepted ECA.

Seems to be working now. :smile: 

> Not sure how to proceed on you other comment, would a new unittest need to be added?

Having unit tests for the code in question would be very nice, but seems a bit too much to ask for in the context of this PR.

To prevent this specifc issue from happening again we'd need to make sure at least one target gets built with this define (LWM2M_RAW_BLOCK1_REQUESTS) enabled. And also, that at least one keeps getting built without this flag.

I think the best way to ensure this would be to create a new build job which compiles the sources both ways and lets the unit tests run. I opened up a new issue #588 for this, and I plan on implementing it soon.

Therefore, I will merge this PR.

Thanks a lot and welcome to the project!

2021-04-16 10:47 UTC, rettichschnidi approved these changes

2021-04-16 10:47 UTC, merged